# Generated by Django 4.2 on 2023-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_skills',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_skills',
            field=models.ManyToManyField(to='mypage.skills'),
        ),
    ]
