# Generated by Django 4.2 on 2023-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files')),
            ],
        ),
    ]
